### ISSUE TITLE
Resample

### ISSUE THREAD

**Issue by Tsironisa** [pytroll/satpy#1446] opened 2020-11-20 14:44 UTC
**Describe the bug**
after resampling the new scene has no data
**To Reproduce**

```python
scn = scn.resample("eurol")
scn.available_dataset_ids()

```

**Expected behavior**
a list of IDs

**Actual results**
[]

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.config import check_satpy; check_satpy()`]

**Additional context**

**Comment by djhoese** [comment] 2020-11-20 15:11
Thanks for asking the question. The `available_dataset_ids` method is meant to show what is loadable from the readers you created your Scene with. By design (although poorly documented), Satpy does not retain access to the readers after you resample.

Put another way, your `.load` calls and `.available_dataset_ids` calls should be done **before** `.resample`.

**Comment by Tsironisa** [comment] 2020-11-20 15:29
thank you for your quick answer.it was my fault to believe that after sampling there is no data.what led me to that conclusion was the fact that when i try to load a composite containing HRV channel i get a error unknow datasets

my code is this:

scn=scn.resample("eurol")
composite ='hrv_clouds'
scn.load([composite])

this is the error

KeyError: "Unknown datasets: {DataQuery(name='HRV', modifiers=('sunz_corrected',)): {DataQuery(name='HRV', modifiers=())}, DataQuery(name='IR_108'): {DataQuery(name='IR_108')}}"

i think i need the resample to use HRV channel .if i do without resample i get:
Chunks do not add up to shape. Got chunks=((3711, 3711, 3714),), shape=(8192,) 

can you help me use the HRV channel?

i use native reader for MSG seviri data

**Comment by djhoese** [comment] 2020-11-20 15:33
How are you creating your Scene? Are you providing all the necessary files?

That chunks error I think is something that has just been fixed in pyresample (but not yet released). I think @pnuu was the one who fixed it.

**Comment by Tsironisa** [comment] 2020-11-20 15:38
i load files with this 
my_files = find_files_and_readers(base_dir= 'test',  
                                   reader='seviri_l1b_native')
scn= Scene(filenames=my_files)

and with scn.available_dataset_ids() i can see all the necessery files are there

**Comment by gerritholl** [comment] 2020-11-20 18:04
To check what data are actually in your scene, you can try `scn.keys()`.

**Comment by djhoese** [comment] 2020-11-20 18:15
@Tsironisa Would you mind installing the development version of pyresample and see if that fixes the resample step:

```
pip install --no-deps git+https://github.com/pytroll/pyresample.git
```

Then run your python code as usual. That should *hopefully* get rid of the chunks error.

**Comment by Tsironisa** [comment] 2020-11-21 18:11
yes everything is fine now ! thank you very much

**Comment by djhoese** [comment] 2020-11-22 01:20
Thanls for checking. We'll try to make a patch release in the next week or so. I'll close this for now. Feel free to comment if you run into the same issue later.

**Closed** 2020-11-22 01:20 UTC
Labels: question
