### ISSUE TITLE
The `viirs_sdr` reader does not function correctly with `GMODO` geolocation.

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#1786] opened 2021-08-09 15:41 UTC
**Describe the bug**
VIIRS data comes with two types of geolocation file, one that is corrected for terrain (f.ex `GMTCO` for M-bands) and one that is not (`GMODO`).
By default, the NOAA CLASS website provides users with `GMODO` files rather than `GMTCO` and these files do not work properly with satpy: It requires `GMTCO`, which is unexpected.

**To Reproduce**

```python
# Find files
files = find_files_and_readers(base_dir=f'{indir}/*', reader='viirs_sdr')

# Create scene and load a composite
scn = Scene(files, reader='viirs_sdr')
scn.load(['true_color_raw'])
# Resample to an area def
scn2 = scn.resample('omerc_bb', resampler='nearest')

# Save results
scn2.save_datasets()
```

**Expected behavior**
A TIFF file to be created showing a true colour image of the specified region.

**Actual results**
An error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in precompute(self, mask, radius_of_influence, epsilon, cache_dir, **kwargs)
    521         try:
--> 522             self.load_neighbour_info(cache_dir, mask=mask, **kwargs)
    523             LOG.debug("Read pre-computed kd-tree parameters")

c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in load_neighbour_info(self, cache_dir, mask, **kwargs)
    586             else:
--> 587                 raise IOError
    588         self._index_caches[mask_name] = cached

OSError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
C:\Users\EUMETC~1\AppData\Local\Temp/ipykernel_25560/2652493872.py in <module>
      1 scn = Scene(files, reader='viirs_sdr')
      2 scn.load(['markuse_fire_original', 'markuse_fire_nir'])
----> 3 scn2 = scn.resample('omerc_bb', resampler='nearest')
      4 scn2.save_datasets()

c:\users\eumetcast#\pycharmprojects\satpy\satpy\scene.py in resample(self, destination, datasets, generate, unload, resampler, reduce_data, **resample_kwargs)
    810             destination = self.finest_area(datasets)
    811         new_scn = self.copy(datasets=datasets)
--> 812         self._resampled_scene(new_scn, destination, resampler=resampler,
    813                               reduce_data=reduce_data, **resample_kwargs)
    814 

c:\users\eumetcast#\pycharmprojects\satpy\satpy\scene.py in _resampled_scene(self, new_scn, destination_area, reduce_data, **resample_kwargs)
    771             kwargs = resample_kwargs.copy()
    772             kwargs['resampler'] = resamplers[source_area]
--> 773             res = resample_dataset(dataset, destination_area, **kwargs)
    774             new_datasets[ds_id] = res
    775             if ds_id in new_scn._datasets:

c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in resample_dataset(dataset, destination_area, **kwargs)
   1388 
   1389     fill_value = kwargs.pop('fill_value', get_fill_value(dataset))
-> 1390     new_data = resample(source_area, dataset, destination_area, fill_value=fill_value, **kwargs)
   1391     new_attrs = new_data.attrs
   1392     new_data.attrs = dataset.attrs.copy()

c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in resample(source_area, data, destination_area, resampler, **kwargs)
   1351         res = [resampler_instance.resample(ds, **kwargs) for ds in data]
   1352     else:
-> 1353         res = resampler_instance.resample(data, **kwargs)
   1354 
   1355     return res

c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in resample(self, data, cache_dir, mask_area, **kwargs)
    438             kwargs['mask'] = kwargs['mask'].all(dim=flat_dims)
    439 
--> 440         cache_id = self.precompute(cache_dir=cache_dir, **kwargs)
    441         return self.compute(data, cache_id=cache_id, **kwargs)
    442 

c:\users\eumetcast#\pycharmprojects\satpy\satpy\resample.py in precompute(self, mask, radius_of_influence, epsilon, cache_dir, **kwargs)
    524         except IOError:
    525             LOG.debug("Computing kd-tree parameters")
--> 526             self.resampler.get_neighbour_info(mask=mask)
    527             self.save_neighbour_info(cache_dir, mask=mask, **kwargs)
    528 

D:\miniconda3\lib\site-packages\pyresample\kd_tree.py in get_neighbour_info(self, mask)
   1064         # Create kd-tree
   1065         chunks = mask.chunks if mask is not None else CHUNK_SIZE
-> 1066         valid_input_idx, resample_kdtree = self._create_resample_kdtree(
   1067             chunks=chunks)
   1068         self.valid_input_index = valid_input_idx

D:\miniconda3\lib\site-packages\pyresample\kd_tree.py in _create_resample_kdtree(self, chunks)
   1015     def _create_resample_kdtree(self, chunks=CHUNK_SIZE):
   1016         """Set up kd tree on input."""
-> 1017         source_lons, source_lats = self.source_geo_def.get_lonlats(
   1018             chunks=chunks)
   1019         valid_input_idx = ((source_lons >= -180) & (source_lons <= 180) &

D:\miniconda3\lib\site-packages\pyresample\geometry.py in get_lonlats(self, data_slice, chunks, **kwargs)
    224             if isinstance(lons, da.Array):
    225                 # rechunk to this specific chunk size
--> 226                 lons = lons.rechunk(chunks)
    227                 lats = lats.rechunk(chunks)
    228             elif not isinstance(lons, da.Array):

D:\miniconda3\lib\site-packages\dask\array\core.py in rechunk(self, chunks, threshold, block_size_limit, balance)
   2512         from . import rechunk  # avoid circular import
   2513 
-> 2514         return rechunk(self, chunks, threshold, block_size_limit, balance)
   2515 
   2516     @property

D:\miniconda3\lib\site-packages\dask\array\rechunk.py in rechunk(x, chunks, threshold, block_size_limit, balance)
    251     if isinstance(chunks, (tuple, list)):
    252         chunks = tuple(lc if lc is not None else rc for lc, rc in zip(chunks, x.chunks))
--> 253     chunks = normalize_chunks(
    254         chunks, x.shape, limit=block_size_limit, dtype=x.dtype, previous_chunks=x.chunks
    255     )

D:\miniconda3\lib\site-packages\dask\array\core.py in normalize_chunks(chunks, shape, limit, dtype, previous_chunks)
   2822             for c, s in zip(map(sum, chunks), shape)
   2823         ):
-> 2824             raise ValueError(
   2825                 "Chunks do not add up to shape. "
   2826                 "Got chunks=%s, shape=%s" % (chunks, shape)

ValueError: Chunks do not add up to shape. Got chunks=((768, 332, 436, 664, 104, 768), (1100, 1100, 1000)), shape=(9216, 3200)
```
I have tried this with multiple granules and multiple resampling methods (EWA, nearest, bilinear, bucket average) and both with and without `reduce_data`. None work, and the problem is only resolved by adding the `GMTCO` file.

**Environment Info:**
 - OS: Windows and linux
 - Satpy Version: Latest from conda
 - PyResample Version: Latest from conda

**Comment by djhoese** [comment] 2021-08-09 18:35
Try installing pyresample from the `main` branch on github. This error is specifically due to the EWA resampling doing something that isn't compatible with new versions of dask but has been fixed on the main branch. If you are getting a different error when working with other resampling methods then please paste those tracebacks here.

**Comment by simonrp84** [comment] 2021-08-09 19:18
Aah sorry, @djhoese you're right: I get a different error with `ewa` compared to other resamplers. I've now edited my initial post to show the error produced by `nearest`.

**Comment by djhoese** [comment] 2021-08-09 19:41
Can you print out what files are actually being found? It seems to be combining different resolutions.

**Comment by simonrp84** [comment] 2021-08-09 19:45
Here you go:
```
GMODO_npp_d20190914_t0552026_e0557430_b40829_c20190914095758939733_noac_ops.h5
SVM01_npp_d20190914_t0552026_e0557430_b40829_c20190914095758866781_noac_ops.h5
SVM02_npp_d20190914_t0552026_e0557430_b40829_c20190914095758901444_noac_ops.h5
SVM03_npp_d20190914_t0552026_e0557430_b40829_c20190914095758905511_noac_ops.h5
SVM04_npp_d20190914_t0552026_e0557430_b40829_c20190914095758910111_noac_ops.h5
SVM05_npp_d20190914_t0552026_e0557430_b40829_c20190914095758915234_noac_ops.h5
SVM06_npp_d20190914_t0552026_e0557430_b40829_c20190914095758919819_noac_ops.h5
SVM07_npp_d20190914_t0552026_e0557430_b40829_c20190914095758925837_noac_ops.h5
SVM08_npp_d20190914_t0552026_e0557430_b40829_c20190914095758930413_noac_ops.h5
SVM09_npp_d20190914_t0552026_e0557430_b40829_c20190914095758934806_noac_ops.h5
SVM10_npp_d20190914_t0552026_e0557430_b40829_c20190914095758871173_noac_ops.h5
SVM11_npp_d20190914_t0552026_e0557430_b40829_c20190914095758875889_noac_ops.h5
SVM12_npp_d20190914_t0552026_e0557430_b40829_c20190914095758880320_noac_ops.h5
SVM13_npp_d20190914_t0552026_e0557430_b40829_c20190914095758884372_noac_ops.h5
SVM14_npp_d20190914_t0552026_e0557430_b40829_c20190914095758888321_noac_ops.h5
SVM15_npp_d20190914_t0552026_e0557430_b40829_c20190914095758892292_noac_ops.h5
SVM16_npp_d20190914_t0552026_e0557430_b40829_c20190914095758896358_noac_ops.h5
```

**Comment by djhoese** [comment] 2021-08-10 01:06
As a test, could you try passing `use_tc=False` to your `reader_kwargs` and see if that changes things? Also, what version of Satpy are you using? I merged a PR recently that fixed some "number of scan lines" issues in the VIIRS SDR reader when there were multiple granules in a single file. That hasn't been released yet either.

**Comment by simonrp84** [comment] 2021-08-10 08:26
Thanks, if I add `reader_kwargs={'use_tc': False}` then the code works as expected.
This is with a recent version from github, and includes your VIIRS pull request changes.

**Comment by djhoese** [comment] 2021-08-10 11:23
Ok, one more thing, do you only have the non-TC files available? There is code in the viirs_sdr reader to use the attributes inside the SDR files to find the related geolocation files if they exist. So even if you only provide the non-TC files I think it will still look for the TC files if they are there.

**Comment by simonrp84** [comment] 2021-08-10 14:21
Yes, I only have the non-TC files.
Usually I also order the TC-files, but forgot this time - and as the non-TC files are the default option on NOAA CLASS I think it'd be good to be able to support them without having to supply a keyword. Can `use_tc=False` be the default?

**Comment by djhoese** [comment] 2021-08-10 14:23
>  and as the non-TC files are the default option on NOAA CLASS I think it'd be good to be able to support them without having to supply a keyword

I personally don't know why they are the default in CLASS. I think in most cases people need/want the TC files. Anyway...my personal opinion. They are meant to be supported, this is a bug.

> Can use_tc=False be the default?

No. At least not in my opinion. If you have TC files then they should be used and we fall back to the non-TC files. That's the way it is supposed to work. People who use CLASS and went the through the extra step to download the TC data shouldn't have to also specify an additional flag to use them. Again, my opinion.

**Comment by simonrp84** [comment] 2021-08-10 14:29
I agree on both points!
Re. default option: What I meant was that by default Satpy will process using the non-TC files if those are all that's available. I meant that processing shouldn't depend on needing the user to specify the extra flag.

I don't know the code for VIIRS that well, is this something you can change when you have the time? If not, I can try investigating but it'll not be a quick process!

**Comment by djhoese** [comment] 2021-08-10 14:32
I'm looking at it right now. Do you know if these are multiple granules in a single file? Using my local files and not providing the TC files it is still working. I'll keep trying things.

**Comment by djhoese** [comment] 2021-08-10 14:40
@simonrp84 I'm unable to reproduce this. Could you put your files somewhere I can get to them? I have single granule files and multiple of them. If I do the following which loads multiple GIMGO files and multiple SVI04 files it works fine.

```python
In [2]: scn = Scene(reader="viirs_sdr", filenames=glob("/tmp/viirs_notc/*.h5"))

In [3]: scn.load(["I04"])

In [4]: scn["I04"].attrs["area"].lons.chunks
Out[4]: ((1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536), (4096, 2304))

In [5]: scn["I04"].chunks
Out[5]: ((1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536), (4096, 2304))

In [6]: new_scn = scn.resample("moll", resampler="nearest")

In [7]: new_scn.save_datasets(base_dir="/tmp")

In [8]: scn["I04"].attrs["area"].lons.chunks
Out[8]: ((1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536, 1536), (4096, 2304))

In [9]: scn["I04"].attrs["area"].lons.attrs
Out[9]:
{'start_orbit': 17783,
 'end_orbit': 17783,
 'file_key': 'All_Data/{dataset_group}_All/Longitude',
 'standard_name': 'longitude',
 'name': 'i_longitude',
 'units': 'degrees_east',
 'rows_per_scan': 32,
 'dataset_groups': ['GIMGO'],
 'dataset_group': 'GIMGO',
 'file_units': 'degrees_east',
 'file_type': 'generic_file',
 'sensor': 'viirs',
 'coordinates': ('i_longitude', 'i_latitude'),
 'resolution': 371,
 'platform_name': 'Suomi-NPP',
 'modifiers': (),
 'start_time': datetime.datetime(2016, 9, 7, 18, 51, 45, 942356),
 'end_time': datetime.datetime(2016, 9, 7, 19, 5, 59, 89951),
 '_satpy_id': DataID(name='i_longitude', resolution=371, modifiers=()),
 'long_name': 'longitude',
 'ancillary_variables': []}
```

You can see in the attrs of the longitude DataArray that it was produced from the GIMGO file instead of finding any GITCO file.

I'll try with some M bands...

**Comment by djhoese** [comment] 2021-08-10 14:44
Do you have a custom chunk size set?

**Comment by simonrp84** [comment] 2021-08-10 14:50
Bear in mind that I'm creating a composite rather than just loading a band. In my original post I'm loading `true_color_raw` but I've tried other composites too.

Yes, I have a custom chunk size of `1024`. But commenting out that line in my environment variables doesn't change the result.
If it's any help, I also get this message right before processing fails: `Can't find appropriate azimuth.`

I've uploaded a copy of the files needed for `true_color` here: http://weatherstationdata.physics.ox.ac.uk/Visualisations/VIIRS.zip

**Comment by djhoese** [comment] 2021-08-10 14:51
I tried `true_color_raw` and it still wasn't a problem. The chunk sizes produced in your output are suspect. It seems like your granules are being separated in a weird way. I'll try downloading your data and looking into it. Thanks.

**Comment by djhoese** [comment] 2021-08-10 15:12
Ok so good news is I can reproduce it with your files.

The "Can't find appropriate azimuth" seems to be coming from pyresample when trying to handle "omerc_bb". Doing it with "moll" it still fails but no azimuth warning.

The chunk sizes on my machine with current main of Satpy are a consistent 768 which I'm guessing is what you see when you are doing this with current main. The error message shows that there are 8 granules of 768 rows each. The resulting shape though says 18432 which is 3x that. If you look at the individual lon/lat shapes you see that they are the reason for the 3x multiplier:

```python
In [10]: scn["true_color_raw"].attrs["area"].lats.shape
Out[10]: (18432, 3200)

In [11]: scn["true_color_raw"].attrs["area"].lons.shape
Out[11]: (18432, 3200)

In [12]: scn["true_color_raw"].shape
Out[12]: (3, 6144, 3200)

In [13]: scn["true_color_raw"].chunks
Out[13]: ((1, 1, 1), (768, 768, 768, 768, 768, 768, 768, 768), (3200,))
```

Now to investigate the file contents...

**Comment by djhoese** [comment] 2021-08-10 16:36
See #1787

**Comment by simonrp84** [comment] 2021-08-11 08:21
Thanks Dave.
I just tested this and it works! No errors and the output file is created successfully.

I do, though, get a bunch of warnings:
```Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'solar_azimuth_angle'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'solar_azimuth_angle'
Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'i_longitude'
Required file type 'generic_file' not found or loaded for 'i_latitude'
Required file type 'generic_file' not found or loaded for 'solar_azimuth_angle'
Required file type 'generic_file' not found or loaded for 'solar_zenith_angle'
Required file type 'generic_file' not found or loaded for 'I01'
Required file type 'generic_file' not found or loaded for 'satellite_zenith_angle'
Required file type 'generic_file' not found or loaded for 'satellite_azimuth_angle'
Can't find appropriate azimuth.
```

**Comment by simonrp84** [comment] 2021-08-11 10:44
No, before only the last message (azimuth) showed up. The others did not.

**Comment by djhoese** [comment] 2021-08-12 00:02
When do you see these messages? Locally I'm unable to reproduce them. I only got messages like that when I tried to load `true_color_raw` but had forgotten to provide more than SVM03 and GMODO files from your provided data. Once I did then it worked fine:

```python
In [4]: scn = Scene(reader='viirs_sdr', filenames=glob("SVM*.h5") + glob("GMODO*.h5"))

In [5]: scn.load(["true_color_raw"])

In [6]: new_scn = scn.resample("omerc_bb", resampler="nearest")
Can't find appropriate azimuth.
/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pyproj/crs/crs.py:1216: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  return self._crs.to_proj4(version=version)
```

**Comment by djhoese** [comment] 2021-08-13 12:42
@simonrp84 any updates on this?

**Closed** 2021-08-16 16:24 UTC
