### ISSUE TITLE
'NoData' area is not black(clean) in the Sentinel-2 MSI output

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1727] opened 2021-06-12 09:30 UTC
**Describe the bug**
I generate an image with `fill_value=0` option, but the result is 1. This will cause problems when doing mosaic.
![image](https://user-images.githubusercontent.com/72339781/121771392-abf40000-cba1-11eb-937a-10c52ed996cc.png)

Without `fill_value=0`, there should be an alpha band with transparent area, however the outcome is black this time. Also the alpha band is completely white.
![image](https://user-images.githubusercontent.com/72339781/121771569-ad71f800-cba2-11eb-8c5e-c45873d58c11.png)

This happens on every 'edge' dataset I've tested, whether atmospheric corrected or not.

**To Reproduce**

```python
#!/usr/bin/env python
from satpy import Scene, find_files_and_readers
files = find_files_and_readers(base_dir="/mnt/hgfs/Downloads/Sat/",
                               reader='msi_safe')
scn = Scene(filenames=files)
composite = 'true_color_raw'
scn.load([composite])
scn.save_dataset(composite, filename='{name}_{start_time:%Y%m%d_%H%M%S}.tif', writer='geotiff', base_dir="/mnt/hgfs/Downloads/Sat/", num_threads=8, compress=None)

```

**Expected behavior**
'NoData' area should be set correctly.

**Environment Info:**
 - OS: Ubuntu 20.04 64bit
 - Satpy Version: 0.29

**Additional context**

**Comment by mraspaud** [comment] 2021-06-12 11:10
Thanks @yukaribbba for reporting this issue. 

It is strange, but maybe the no data value is wrongly assigné in the msi safe reader?

I will try to have a look on Monday if no one beats me to it.

**Comment by yukaribbba** [comment] 2021-06-12 12:12
@mraspaud Thanks. I just discovered it yesterday but I think it could’ve been here for some time since it also exists in the images generated several months ago.

**Comment by mraspaud** [comment] 2021-06-12 12:29
Ah, the problem is that the data is integers. We should convert it to floats in the reader.

**Comment by mraspaud** [comment] 2021-06-14 07:21
@yukaribbba ok, I had a better look, and the problem is simply that the no-data value is never defined in the reader. According to the MTD file, it should be zero. I don't have much time right now, so if you want to give it a try... it's just about replacing zeros in the data with `np.nan`.

**Comment by yukaribbba** [comment] 2021-06-14 09:00
@mraspaud Sorry I'm not good at coding...so could you give me more hints about this? Thanks

**Comment by mraspaud** [comment] 2021-06-14 09:18
I was thinking that around here: https://github.com/pytroll/satpy/blob/main/satpy/readers/msi_safe.py#L79
we should add something like `data = da.where(data > 0, data, np.nan)`

But I can try to do a PR later today

**Comment by yukaribbba** [comment] 2021-06-14 09:44
@mraspaud I just found an image created last April, by 0.20 or 0.21, not sure. No problem there. So maybe it's due to the changes of some dependencies?

**Comment by mraspaud** [comment] 2021-06-14 11:18
@yukaribbba I now completed the PR I made earlier (#1628) and added the masking of the invalid data. I also added tests, so hopefully that PR can now be merged. Would you mind testing this and tell me if it fixes your problem?

**Comment by yukaribbba** [comment] 2021-06-14 13:47
@mraspaud It truely works. I've tested about 100 datasets and both issues got fixed. Thank you!

**Comment by mraspaud** [comment] 2021-06-15 06:27
Thanks for testing! I will merge the PR now.

**Closed** 2021-06-15 06:28 UTC
Labels: bug, component:readers
