### ISSUE TITLE
Fails displaying the NWCSAF/Geo cloud products correctly

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#2376] opened 2023-02-02 14:00 UTC
**Describe the bug**

I am reading and displaying the NWCSAF/geo cloud products, specifically the Cloud Type. I am loading the `cloudtype` composite. Using the standard enhancements defined in the `generic.yaml`. However, the result is an image in B/W. The GeoTiff does actually seem to contain RGB values, but the look is black and white, see below.

 

**To Reproduce**

```python
# Your code here
geo_files = glob(os.path.join(DATADIR, "S_NWC_*_MSG4_MSG-N-VISIR_20230201T1700*_PLAX.nc"))
scn = Scene(filenames=geo_files, reader='nwcsaf-geo')
scn.load(['ct', 'cloudtype'])
scn.show('cloudtype')
```

Below are the imagery after resampling:
```
local = scn.resample(areaid, radius_of_influence=20000)
stime = datetime.strftime(local.start_time, '%Y%m%d_%H%M')
local.save_dataset('cloudtype', filename='./cloudtype_geo_{time}.tiff'.format(time=stime))
```

I have tested the same with the NWCSAF/PPS files, and there it looks correct.

**Expected behavior**
I expect the imagery as shown here below, created with Satpy 0.39.0. First one is the Geo product, the second is the PPS cloudtype:

![cloudtype_geo_20230201_1709_satpy039](https://user-images.githubusercontent.com/169069/216344551-75193426-706f-4384-8d1c-63df711aa6a4.png)

![cloudtype_pps_20230201_1657_satpy039](https://user-images.githubusercontent.com/169069/216344565-65be90e1-5db2-4ece-b937-42b0d25d9b78.png)

**Actual results**
I don't see any errors, but below is the debug info from trying to display the Geo Cloudtype:

```
/home/a000680/usr/src/forks/satpy/satpy/_config.py:129: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in cached_entry_points().get(name, []):
[DEBUG: 2023-02-02 14:19:30 : satpy.readers.yaml_reader] Reading ('/home/a000680/usr/src/forks/satpy/satpy/etc/readers/nwcsaf-geo.yaml',)
[DEBUG: 2023-02-02 14:19:30 : satpy.readers.yaml_reader] Assigning to nwcsaf-geo: ['/home/a000680/data/mesan/geo_in/v2021/S_NWC_CT_MSG4_MSG-N-VISIR_20230201T170000Z_PLAX.nc']
[DEBUG: 2023-02-02 14:19:30 : rasterio.session] Could not import boto3, continuing with reduced functionality.
[DEBUG: 2023-02-02 14:19:30 : satpy.composites.config_loader] Looking for composites config file seviri.yaml
[DEBUG: 2023-02-02 14:19:30 : pyorbital.tlefile] Path to the Pyorbital configuration (where e.g. platforms.txt is found): /home/a000680/usr/src/forks/pyorbital/pyorbital/etc
[DEBUG: 2023-02-02 14:19:31 : satpy.composites.config_loader] Looking for composites config file visir.yaml
/home/a000680/usr/src/forks/satpy/satpy/_config.py:129: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in cached_entry_points().get(name, []):
[DEBUG: 2023-02-02 14:19:31 : satpy.readers.nwcsaf_nc] Reading ct.
[DEBUG: 2023-02-02 14:19:31 : h5py._conv] Creating converter from 7 to 5
[DEBUG: 2023-02-02 14:19:31 : h5py._conv] Creating converter from 5 to 7
[DEBUG: 2023-02-02 14:19:31 : h5py._conv] Creating converter from 7 to 5
[DEBUG: 2023-02-02 14:19:31 : h5py._conv] Creating converter from 5 to 7
[WARNING: 2023-02-02 14:19:31 : satpy.readers.yaml_reader] Can't load ancillary dataset ct_status_flag
[DEBUG: 2023-02-02 14:19:31 : satpy.readers.nwcsaf_nc] Reading ct_conditions.
[DEBUG: 2023-02-02 14:19:31 : satpy.readers.nwcsaf_nc] Reading ct_pal.
[DEBUG: 2023-02-02 14:19:31 : satpy.readers.yaml_reader] No coordinates found for DataID(name='ct_pal', resolution=3000, modifiers=())
[DEBUG: 2023-02-02 14:19:31 : satpy.readers.nwcsaf_nc] Reading ct_quality.
[DEBUG: 2023-02-02 14:19:31 : satpy.scene] Resampling DataID(name='cloudtype', resolution=3000)
/home/a000680/mambaforge/envs/python3.10/lib/python3.10/site-packages/pyresample/spherical.py:300: RuntimeWarning: invalid value encountered in divide
  cart = self.cart / norm
[INFO: 2023-02-02 14:19:35 : satpy.resample] Using default KDTree resampler
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Resampling add-9c53791334085fc9396a6002ec2beae0
[DEBUG: 2023-02-02 14:19:35 : satpy.scene] Resampling DataID(name='ct_conditions', resolution=3000, modifiers=())
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Resampling ct_conditions
[DEBUG: 2023-02-02 14:19:35 : satpy.scene] Resampling DataID(name='ct_quality', resolution=3000, modifiers=())
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Resampling ct_quality
[DEBUG: 2023-02-02 14:19:35 : satpy.scene] Resampling DataID(name='ct', resolution=3000, modifiers=())
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Computing kd-tree parameters
[DEBUG: 2023-02-02 14:19:35 : satpy.resample] Resampling ct
[DEBUG: 2023-02-02 14:19:35 : satpy.writers] Reading ['/home/a000680/usr/src/forks/satpy/satpy/etc/writers/geotiff.yaml']
/home/a000680/usr/src/forks/satpy/satpy/_config.py:129: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in cached_entry_points().get(name, []):
[DEBUG: 2023-02-02 14:19:35 : satpy.writers] Adding enhancement configuration from file: /home/a000680/usr/src/forks/satpy/satpy/etc/enhancements/generic.yaml
[DEBUG: 2023-02-02 14:19:35 : satpy.writers] Adding enhancement configuration from file: /home/a000680/usr/src/forks/satpy/satpy/etc/enhancements/seviri.yaml
[DEBUG: 2023-02-02 14:19:35 : satpy.writers] Data for DataID(name='cloudtype', resolution=3000) will be enhanced with options:
	[{'name': 'palettize', 'method': <function palettize at 0x7f6b8b90a7a0>, 'kwargs': {'palettes': [{'dataset': 'ct_pal', 'color_scale': 255}]}}]
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Entering env context: <rasterio.env.Env object at 0x7f6b8c8ad6f0>
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Starting outermost env
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] No GDAL environment exists
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] New GDAL environment <rasterio._env.GDALEnv object at 0x7f6b8ba7a710> created
[DEBUG: 2023-02-02 14:19:36 : rasterio._filepath] Installing FilePath filesystem handler plugin...
[DEBUG: 2023-02-02 14:19:36 : rasterio._env] GDAL_DATA found in environment.
[DEBUG: 2023-02-02 14:19:36 : rasterio._env] PROJ_DATA found in environment.
[DEBUG: 2023-02-02 14:19:36 : rasterio._env] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f6b8ba7a710>.
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Entered env context: <rasterio.env.Env object at 0x7f6b8c8ad6f0>
[DEBUG: 2023-02-02 14:19:36 : rasterio._io] Path: _UnparsedPath(path='./cloudtype_20230201_1709.tiff'), mode: w, driver: GTiff
[DEBUG: 2023-02-02 14:19:36 : rasterio._base] Nodata success: 0, Nodata value: 0.000000
[DEBUG: 2023-02-02 14:19:36 : rasterio._base] Nodata success: 0, Nodata value: 0.000000
[DEBUG: 2023-02-02 14:19:36 : rasterio._base] Nodata success: 0, Nodata value: 0.000000
[DEBUG: 2023-02-02 14:19:36 : rasterio._base] Nodata success: 0, Nodata value: 0.000000
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Exiting env context: <rasterio.env.Env object at 0x7f6b8c8ad6f0>
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Cleared existing <rasterio._env.GDALEnv object at 0x7f6b8ba7a710> options
[DEBUG: 2023-02-02 14:19:36 : rasterio._env] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f6b8ba7a710>.
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Exiting outermost env
[DEBUG: 2023-02-02 14:19:36 : rasterio.env] Exited env context: <rasterio.env.Env object at 0x7f6b8c8ad6f0>
/home/a000680/mambaforge/envs/python3.10/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in cos
  return func(*(_execute_task(a, cache) for a in args))
/home/a000680/mambaforge/envs/python3.10/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in sin
  return func(*(_execute_task(a, cache) for a in args))
```

And here is the result of running gdalinfo on the Tiff image:
```

(python3.10) ➜  nwcsaf gdalinfo cloudtype_20230201_1709.tiff
Driver: GTiff/GeoTIFF
Files: cloudtype_20230201_1709.tiff
Size is 1024, 1024
Coordinate System is:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["Unknown based on Bessel 1841 ellipsoid",
            ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Polar Stereographic (variant B)",
        METHOD["Polar Stereographic (variant B)",
            ID["EPSG",9829]],
        PARAMETER["Latitude of standard parallel",60,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8832]],
        PARAMETER["Longitude of origin",14,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8833]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",south,
            MERIDIAN[90,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",south,
            MERIDIAN[180,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[2],
            LENGTHUNIT["metre",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (-2717181.730499468743801,-1475048.140312139876187)
Pixel Size = (4000.000000000000000,-4000.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2023:02:01 17:09:17
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-2717181.730,-1475048.140) ( 47d30'15.31"W, 60d56'39.45"N)
Lower Left  (-2717181.730,-5571048.140) ( 12d 0' 0.00"W, 35d 0' 0.00"N)
Upper Right ( 1378818.270,-1475048.140) ( 57d 4' 7.57"E, 70d47'52.68"N)
Lower Right ( 1378818.270,-5571048.140) ( 27d54' 4.30"E, 38d32'48.36"N)
Center      ( -669181.730,-3523048.140) (  3d14'42.47"E, 56d32' 0.61"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA
Band 4 Block=256x256 Type=Byte, ColorInterp=Alpha
```

**Screenshots**

![cloudtype_geo_20230201_1709_latest_satpy](https://user-images.githubusercontent.com/169069/216343773-cc879dcb-1e44-4914-9fde-57901f80d14a.png)
![cloudtype_pps_20230201_1657_latest_satpy](https://user-images.githubusercontent.com/169069/216343807-52aae68f-63c9-4366-897c-4cbf7121c33f.png)

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: latest main - towards `0.40.0`
 - PyResample Version: `1.26.0`
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by gerritholl** [comment] 2023-02-02 14:06
I'm surprised NWCSAF/PPS is not affected.  Is the resulting image mode P or mode RGB?

I introduced this bug in #2313 and #2373.  The idea with #2313 was that loading a composite would produce mode P and to unify the ways the colormap is attached.  But where does Satpy load `cloudtype` from when loading it for NWCSAF/PPS?  I would expect it would be the same for PPS and GEO.  Understanding why it affects one but not the other may help me understand the bug.

If you save the image to GeoTIFF with `keep_palette=True`, do both result in a mode P image?

**Comment by gerritholl** [comment] 2023-02-03 09:00
Commenting out those lines (or replacing `if set_range` by `if False`) the image looks correct:

https://github.com/pytroll/trollimage/blob/0c7bbad6581010d8be089e5e0589524cf2cd073f/trollimage/colormap.py#L685-L688

Satpy and trollimage are inadvertently scaling the values corresponding to the colormap to cover the valid range, such that 256 colors are stretched to values between 1 and 15.  The first 15 of those colors are all black.

I don't know yet why that didn't happen before I moved the code to trollimage.

**Comment by gerritholl** [comment] 2023-02-03 10:08
With https://github.com/pytroll/trollimage/pull/123 the images look like:

CRR:

![METEOSATNOWCSAF_EUROPA_GESAMT_CRR_nqeuro3km_202302030945-geotiff](https://user-images.githubusercontent.com/500246/216572466-2eafa2ac-4469-452f-adda-c4451df6ec5e.png)

CT:

![METEOSATNOWCSAF_EUROPA_GESAMT_CT_nqeuro3km_202302030945-geotiff](https://user-images.githubusercontent.com/500246/216572433-86898a4b-3b48-4c60-951b-b9f9309701fb.png)

CTH:

![METEOSATNOWCSAF_EUROPA_GESAMT_CTH_nqeuro3km_202302030945-geotiff](https://user-images.githubusercontent.com/500246/216572455-18d79e83-668a-441e-880b-59b2830439bc.png)

PC:

![METEOSATNOWCSAF_EUROPA_GESAMT_PC_nqeuro3km_202302030945-geotiff](https://user-images.githubusercontent.com/500246/216572409-f48e0509-11b7-4ab9-8cd2-a6e49b21d393.png)

Testing others is a bit more involved for me because we only produce those four products from NWCSAF/GEO.  If people have other NWCSAF/GEO products I can test those or others can test them directly.

**Comment by mraspaud** [comment] 2023-02-03 13:08
Looks correct to me!

**Comment by mraspaud** [comment] 2023-02-03 20:12
Closing as this is solved in the latest release of trollimage, and @adybbroe confirmed getting correct results on slack.

**Closed by mraspaud** 2023-02-03 20:12 UTC
Labels: bug
