### ISSUE TITLE
There is a bug in 'find_files_and_readers(reader='modis_l2)''

### ISSUE THREAD

**Issue by yhyxzx** [pytroll/satpy#2298] opened 2022-11-24 14:07 UTC
**Describe the bug**
It didn't work as a filter.

**To Reproduce**

```python
MOD_dir = 'F:/yydata/MODIS/'
Y=2022
M=10
D=7
h=1
m=45
MO_cloud_name = find_files_and_readers(start_time=datetime.datetime(Y, M, D, h, m),
                                       base_dir=MOD_dir,
                                       reader='modis_l2')
print(MO_cloud_name)

```

**Expected behavior**
The correct result is {'modis_l2': ['F:/yydata/MODIS\\MOD35_L2.A2022113.0325.061.2022113133154.hdf', 'F:/yydata/MODIS\\MOD03.A2022280.0145.061.2022280064847.hdf']}

**Actual results**
{'modis_l2': ['F:/yydata/MODIS\\MOD35_L2.A2022113.0325.061.2022113133154.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022056.0155.061.2022056133703.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022113.0145.061.2022113133304.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022280.0145.061.2022280130947.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022129.0145.061.2022129133116.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022129.0325.061.2022129133249.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022056.0330.061.2022056133549.hdf', 'F:/yydata/MODIS\\MOD03.A2022280.0145.061.2022280064847.hdf']}

**Comment by djhoese** [comment] 2022-11-24 15:07
I'm not sure on the cause for this yet, but I'm not sure why your expected output should include the `2022113` file? The date you entered as a julian year/day would be 2022280.

**Comment by djhoese** [comment] 2022-11-24 15:14
Ok so the problem is that the filtering is done based on `start_time` from the filename pattern. However, this filename format isn't configured with a `start_time` but instead names it `acquisition_time`. Changing the YAML should be simple enough and could likely mean cleaning up some of the code like this:

https://github.com/pytroll/satpy/blob/6dfb9b9353fa64e91a1f7553783abd859042da56/satpy/readers/hdfeos_base.py#L188-L191

**Comment by yhyxzx** [comment] 2022-11-24 15:18
> I'm not sure on the cause for this yet, but I'm not sure why your expected output should include the `2022113` file? The date you entered as a julian year/day would be 2022280.

Yes，you are right!

**Comment by djhoese** [comment] 2022-11-24 15:29
I don't have time to fix this myself so if you @yhyxzx or anyone else has time it would be appreciated.

**Comment by yhyxzx** [comment] 2022-11-24 15:37
> I don't have time to fix this myself so if you @yhyxzx or anyone else has time it would be appreciated.

I am a new hand. Although I really want to participate, it seems that I am not competent enough to understand your meaning.

**Comment by djhoese** [comment] 2022-11-24 16:13
The first task is to make a pull request where the below YAML file is modified:

https://github.com/pytroll/satpy/blob/6dfb9b9353fa64e91a1f7553783abd859042da56/satpy/etc/readers/modis_l2.yaml#L14

Anywhere it says `acquisition_time` it should be replaced with `start_time`. If you can figure out how to do that (will require knowledge of git) then that should fix the issue.

**Comment by yhyxzx** [comment] 2022-11-26 03:08
reader='modis_l1b' has the same bug. @djhoese

**Comment by djhoese** [comment] 2022-11-26 13:17
We'll close this when #2299 is merged. Reopening for now.

**Closed** 2023-02-02 08:57 UTC
Labels: bug, help wanted, component:readers
