### ISSUE TITLE
Reader for Арктика-М (Arktika-M) МСУ-ГС (MSU-GS) data

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1999] opened 2022-01-28 16:24 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

I would like to read data from the МСУ-ГС (MSU-GS) imager on the Арктика-М № 1 (Arktika-M № 1)  satellite (and subsequent satellites in the Арктика-М series).

**Describe the solution you'd like**

I would like a reader for МСУ-ГС data included with Satpy.

**Describe any changes to existing user workflow**

None foreseen.

**Additional context**

On 2022-01-28, EUMETSAT published sample data for Арктика-М № 1 on their FTP site at ftp://ftp.eumetsat.int/pub/EUM/out/RSO/Arctica-MN1/.  The Арктика satellites were launched by Роскосмос (Roskosmos) and are operated by Росгидромет (Rosgidromet).  They fly in a [Molniya orbit](https://en.wikipedia.org/wiki/Molniya_orbit) with a perigee over the Arctic region.  When the constellation is complete, this will allow for a 24 hour near real time monitoring of the Arctic, similar to how the ring of geostationary satellites provides this functionality for lower latitudes.  The main instrument is the МСУ-ГС imager, which is apparently similar to the ones on the Электро-Л (Elektro-L) satellites, for which Satpy [already has a reader](https://satpy.readthedocs.io/en/stable/api/satpy.readers.electrol_hrit.html).  Some more information about МСУ-ГС  is available [from WMO](https://space.oscar.wmo.int/instruments/view/msu_gs_a).

**Comment by TAlonglong** [comment] 2022-01-28 16:46
Great. No documentation as far as I can see.

This is HDF5 and I guess the other reader mentioned in the issue is HRIT. So I guess we need to start over.

But the format looks like straight forward HDF5.

As far as I can see data comes with lat/lon values. Can not see any projection information.

**Comment by TAlonglong** [comment] 2022-01-28 17:21
Just I quick look at the data:

```
import h5py
from matplotlib import pyplot as plt
import numpy as np
hf = h5py.File('ArcticaM1_202201171330.h5', 'r')
km1=dt.get("/Data/resolution_1km")
plt.imshow(np.dstack([(km1['Radiance_03'][:]*km1['Radiance_03'].attrs['scale']*255/10).astype(int), (km1['Radiance_02'][:]*km1['Radiance_02'].attrs['scale']*255/10).astype(int), (km1['Radiance_01'][:]*km1['Radiance_01'].attrs['scale']*255/10).astype(int)]))
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/19924146/151592584-057f190d-e768-492a-b9a0-99b5bd1e37b5.png)

**Comment by TAlonglong** [comment] 2022-01-28 17:26
You can assign this to me of not someone else want/can spare the time to look at this.

**Closed** 2022-01-31 19:17 UTC
Labels: component:readers
